export const specialties = [
    {value: 0, label: 'Khám chức năng hô hấp'},
    {value: 1, label: 'Khám da liễu'}, 
    {value: 2, label: 'Khám điều trị vết thương'},
    {value: 3, label: 'Khám hậu môn-trực tràng'},
    {value: 4, label: 'Khám mắt'},
    {value: 5, label: 'Khám tai mũi họng'},
    {value: 6, label: 'Khám nội tiết'},
    {value: 7, label: 'Khám phụ khoa'}, 
    {value: 8, label: 'Khám thai'},
    {value: 9, label: 'Khám thần kinh'},
    {value: 10, label: 'Khám tiết niệu'},
    {value: 11, label: 'Khám tiêu hoá-gan mật'},
    {value: 12, label: 'Khám tim mạch'},
    {value: 13, label: 'Khám tổng quát'}, 
    {value: 14, label: 'Khám viêm gan'},
    {value: 15, label: 'Khám xương khớp'},
    {value: 16, label: 'Lồng ngực - Mạch máu - Bướu cổ'},
    {value: 17, label: 'Thẩm mỹ - chăm sóc da'}, 
  ];